NHSDigital/validated-relationships-service-api

- manifest_template.yml
- tests/test_endpoints.py
This change sets the API Product to only allow access to clients where end users have authenticated as NHS Login P9.
It also skips tests which we are not in a position to run yet as they need the API key for the target server to be shared with proxy and a decision about which path on the target server to hit and with which NHS number.
> Set oauth scope for product to P9 and skipped tests pending TBCs

- tests/test_endpoints.py
Added blank lines as linting was failing on Azure DevOps pipelines
> Added blank likes to fix linting error in Azure DevOps

- specification/validated-relationships-service-api.yaml
* Routine Change created for @chris-young-12-nhs 
> NPA 1868 - api catalogue fixes

- specification/validated-relationships-service-api.yaml
Reverts NHSDigital/validated-relationships-service-api as spec changes are breaking schema validation in API tests.
> Revert "NPA-1711: add format qualifier to search params to improve docs and update payload to be FHIR compliant"

- postman/Validate Relationship Service Sandbox.postman_collection.json
Added the postman collection to repository for versioning / updating in the future.
> NPA-1736: Added postman collection to repo for versioning

- proxies/live/apiproxy/policies/AssignMessage.SetRequestAWSMimeType.xml
- proxies/live/apiproxy/targets/target.xml
Updates the preflow for the target server so that any requests with `Content-Type: application/fhir+json` will be converted to `Content-Type: application/json` so AWS can easily transform the request for step functions
> NPA-2676 Update Request MimeType to handle `application/fhir+json`

- proxies/live/apiproxy/targets/target.xml
- specification/validated-relationships-service-api.yaml
https://nhsd-jira.digital.nhs.uk/browse/NPA-2806
- Add support for content type - `application/fhir+json; charset=utf-8`
- Deployed to the dev API and manually tested
> NPA-2806 Support `application/fhir+json; charset=utf-8` Content Type

- specification/validated-relationships-service-api.yaml
https://nhsd-jira.digital.nhs.uk/browse/NPA-3543
These changes to the OAS cover the new `/Consent` API endpoint required for requesting proxy relationships from VRS. For each proxy relationship, there should be three resources:
- Consent (filtering possible based on `status`)
- RelatedPerson (optional _include in the bundle)
- Patient (optional _include in the bundle)
Draft requirements can be found in confluence here (along with details of how to map NAM payloads to FHIR resources): https://nhsd-confluence.digital.nhs.uk/display/NPA/Consent+endpoint+requirements
A summary of expected behaviour of the endpoint:
- Take IM1 connection params in HTTP header in order for VRS to use these against the new NAM endpoint outlined [here](https://nhsd-confluence.digital.nhs.uk/display/NO/Proxy%3A+Ext …
> NPA-3543: add initial /Consent endpoint and associated schema refactoring

- proxies/sandbox/apiproxy/policies/RaiseFault.DefaultError.xml
https://nhsd-jira.digital.nhs.uk/browse/NPA-3877
-  Added CORs headers back to response when sandbox simulates an error
- API Response from internal-dev sandbox
```
* Request completely sent off
< HTTP/1.1 400 BAD REQUEST
< Date: Thu, 31 Oct 2024 12:04:35 GMT
< Content-Type: application/fhir+json
< Content-Length: 361
< Connection: keep-alive
< Server: gunicorn
< Access-Control-Allow-Origin:
< Access-Control-Allow-Headers: origin, x-requested-with, accept, content-type, nhsd-session-urid, authorization, x-correlation-id, x-request-id
< Access-Control-Max-Age: 3628800
< Access-Control-Allow-Methods: GET, PUT, POST, DELETE
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Correlation-ID: 11c46f5f-cdef-4865-94b2-0ee0edcc26da
< X-Request-ID: …
```
> NPA-3877 Update Sandbox CORS on error response

- postman/Validate Relationship Service Sandbox.postman_collection.json
- specification/validated-relationships-service-api.yaml
https://nhsd-jira.digital.nhs.uk/browse/NPA-3545
- X-Request-ID and X-Correlation-ID has been applied to all Postman requests (Related Person + QuestionnaireResponse)
- Exported updated collection to repository
- Updated link to new public collection
- Tested the updated collection and still works with Sandbox
> NPA-3545 Update Postman Collection with X-headers

- specification/validated-relationships-service-api.yaml
https://nhsd-jira.digital.nhs.uk/browse/NPA-4104
- Add description to relatedPerson_relationship to document the direction of the relationship `The directionality of the relationship is from the RelatedPerson (proxy) to the Patient. For example, if the Patient is a child, and the RelatedPerson is the mother, the relationship would be PRN (parent). Crucially, the relationship type is defined by the role that the proxy plays in the relationship.`
> NPA-4104 Document RelatedPerson Relationship Direction

- proxies/live/apiproxy/resources/py/check-app-enabled-endpoint.py
- proxies/live/apiproxy/resources/py/check-user-enabled-endpoint.py
https://nhsd-jira.digital.nhs.uk/browse/NPA-4599
- Updated the python scripts checking if a user or app is authorized to use a particular endpoint to compare the path suffix using contains rather than equals as currently it does not account for path parameters. E.g /FHIR/R4/Consent/c6f48e4d was not being caught in the blocked response for a p9 user.
- Deploy changes to dev and ensure none of the testing suite is failing
- Ensure a user authenticated with p9 access can call the patch Consent endpoint
-   [ ] If there were infrastructure, operational, or build …
> NPA-4599: Update python scripts to check path suffix contains rather than equals specific string to account for path parameters

- sandbox/api/get_questionnaire_response.py
- sandbox/api/tests/test_get_questionnaire_response.py
https://nhsd-jira.digital.nhs.uk/browse/NPA-4693
- Fix Sandbox to return correct status code when reference code is missing
-
-
-
This will run the tests within the collection to check that the sandbox is …
> NPA-4693 Fix MISSING_REFERENCE_CODE Sandbox Response

- specification/validated-relationships-service-api.yaml
https://nhsd-jira.digital.nhs.uk/browse/NPA-4737
- Fix Markdown Tables
-
-
-
> NPA-4737 Fix Markdown Tables

- .github/workflows/run-postman-collection.yml
- postman/Validate Relationship Service Sandbox.postman_collection.json
https://nhsd-jira.digital.nhs.uk/browse/NPA-4922
- Fix Postman Tests
- Run Postman Tests on schedule
- Tests 
This will run the tests within the collection to check that the sandbox is working as expected …
> NPA-4922 Fix Postman Tests

- specification/validated-relationships-service-api.yaml
https://nhsd-jira.digital.nhs.uk/browse/NPA-4913
- Add 502 Errors to all endpoints. The error is generic on the AWS API Gateway and will effect all endpoints.
-
-
-
This will run the tests within the …
> NPA-4913 Add 502 Errors

- specification/validated-relationships-service-api.yaml
https://nhsd-jira.digital.nhs.uk/browse/NPA-5116
Updated specification
- Add generic API authentication documentation
- Add per endpoint authentication documentation
- Docs should align with this table - https://nhsd-confluence.digital.nhs.uk/spaces/NPA/pages/1018846943/API+endpoints+overview
e.g.
-
> NPA-5116 Add API Authentication Documentation

- .github/pull_request_template.md
https://nhsd-jira.digital.nhs.uk/browse/NPA-4330
Standardised and improved PR template
-
-
-
> NPA-4330: Improve PR Template

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/dependency-review.yml
- .github/workflows/openapi-validate.yml
- .github/workflows/prettier-checks.yml
- specification/validated-relationships-service-api.yaml
https://nhsd-jira.digital.nhs.uk/browse/NPA-4986
---
- Fixed a bug where the incorrect error code was in the spec for a 502 error
- General improvements to spec to improve DX
- Ran prettier on `.github` as part of a slow migration to prettify this repository
---
with
---
---
> NPA-4986: Fix Specification Incorrect Error Code

- .github/workflows/run-postman-collection.yml
- sandbox/README.md
https://nhsd-jira.digital.nhs.uk/browse/NPA-5715
---
- Fix incorrect references to Postman Collection
---
- Ran postman collection - https://github.com/NHSDigital/validated-relationships-service-api/actions/runs/18032098819
---
- NA
---
---
---
> NPA-5715: Fix Postman Collection
