NHSDigital/validated-relationships-service-api

specification/validated-relationships-service-api.yaml

* :sparkles: New Feature
Added initial OAS spec file to source control that covers the technical details only; as agreed with IOPS. This forms the basis for iteration by the team.

NPA-1711: add initial OAS file to capture API behaviour

---

specification/validated-relationships-service-api.yaml

Add `_include` query parameter for patient in order to comply with FHIR search semantics and the inclusion of patient in the bundle returned by the endpoint.

NPA-1711_add_include_param_for_patient

---

proxies/live/apiproxy/targets/target.xml

Updated target to point to VRS INT API Gateway

Set target to point to VRS INT API Gateway

---

.github/workflows/pr-lint.yaml

* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change
Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

Update ticket pattern from 'apm' to 'npa'

---

manifest_template.yml
proxies/live/apiproxy/policies/AssignMessage.AddAPIToken.xml
proxies/live/apiproxy/targets/target.xml

Added secret for DEV WAF API token, re-pointed target to DEV environment. Updated description in manifest_template.

Added secret for WAF API token

---

azure/azure-pr-pipeline.yml
manifest_template.yml

Add deployment to the int environment on https://nhs-digital-prod.apigee.com/

NPA-1868: Added int environment

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

Add int to release pipeline and remove (revert) from PR pipeline

NPA-1868: Add int to release pipeline and remove (revert) from PR pipeline

---

README.md

* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change
Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

APM-0000 Test change.

---

azure/azure-release-pipeline.yml

Removed test-command and smoketest-command from release pipeline as they are preventing it from running

NPA-1868: Removed test-command and smoketest-command from release pipeline as they are preventing it from running

---

manifest_template.yml

Added lower environments to manifest_template

NPA-1868: Added lower environments to manifest_template

---

azure/azure-release-pipeline.yml

Temporarily removing post deploy steps to see if I can get a clean deploy to `sandbox` and `int`

Temporarily removing post deploy steps

---

proxies/live/apiproxy/targets/target.xml

Update target server from static URL to a configured Apigee Target Server

Update target server

---

proxies/live/apiproxy/policies/AssignMessage.AddProxyURL.xml
proxies/live/apiproxy/targets/target.xml

Added api.proxy header to use for FIHR compliance

Added api.proxy header to use for FIHR compliance

---

proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml
proxies/live/apiproxy/targets/target.xml

Added a FHIR compliant response to requests which are missing the bearer token.

NPA-2166: Added FHIR compliant response for missing bearer token

---

specification/validated-relationships-service-api.yaml

Changes to ordering of sections in API documentation

Re-ordered sections and updated Strap Line based on feedback from Nathan Kinsler

---

proxies/live/apiproxy/policies/AssignMessage.AddUserAuthLevel.xml

NPA-2051: Fixed typo in adding User Auth Level

---

specification/validated-relationships-service-api.yaml

NPA-1711: add format qualifier to search params to improve docs and update payload to be FHIR compliant

---

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml

* :robot: Operational or Infrastructure Change
This PR updates the CORS polices in the sandbox and live APIM configuration.

NPA-2388 Fix Swagger Try It Now

---

proxies/live/apiproxy/policies/AssignMessage.SetMimeType.xml
proxies/live/apiproxy/targets/target.xml

* Fixing mime type in response to match the spec

Set mime type to application/fhir+json

---

specification/validated-relationships-service-api.yaml

Adds a comment to say the first error encountered will be returned

NPA-2493 Add Error Note for First Error Encountered

---

specification/validated-relationships-service-api.yaml

NPA-2635: Documentation fixes

---

.github/dependabot.yml
.github/workflows/continuous-integration.yml
package-lock.json
package.json
poetry.lock
sandbox/poetry.lock
sandbox/pyproject.toml

This PR contains multiple Dependabot update commits as well as I've run poetry lock and npm update to get newer versions.

NPA-2619 Group All Dependencies Updates

---

specification/validated-relationships-service-api.yaml

NPA-2676: Fixed typo in mime types

---

specification/validated-relationships-service-api.yaml

Fix to mime-type typo first time round was another typo

NPA-2676: Second fix to mime type typo

---

sandbox/api/app.py

Resolved an issue which prevented production from updating due to module import

NPA-1736: Reworked module import to resolve issue with gunicorn

---

specification/validated-relationships-service-api.yaml

NPA-2676: Third fix to mime types

---

specification/validated-relationships-service-api.yaml

Fixes API test:
https://github.com/NHSDigital/proxy-validated-relationships-service/blob/NPA-2676_Receive_Questionnaire/tests/test_api/features/QuestionnaireResponse/3_oauth.feature

NPA-2676: Added 4XX error response

---

proxies/live/apiproxy/policies/RaiseFault.ApplicationOperationOutcome.xml
proxies/live/apiproxy/targets/target.xml

https://nhsd-jira.digital.nhs.uk/browse/NPA-2806
- Re-adds a Fault rule that adds the correct Content-Type on errors from the Application in AWS.
- All requests that pass the 415 Invalid Media Type guard are now transformed to the AWS suitable content type `application/json` or else the request would error.
- Run the automated test suite from the VRS repo and all tests passed.

NPA-2806 Fix Mime Type Response

---

proxies/live/apiproxy/targets/target.xml

https://nhsd-jira.digital.nhs.uk/browse/NPA-2806
-Fixes incorrect content type condition
- Modified the dev API and then ran phase_two tests to prove it works

NPA-2806 Fix incorrect Content-Type Condition

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-3402
- Change Link to Updated Postman Collection in OAS Spec

NPA-3402 Update Link to Postman Collection

---

proxies/live/apiproxy/policies/AssignMessage.AddDeveloperAppId.xml
proxies/live/apiproxy/targets/target.xml

https://nhsd-jira.digital.nhs.uk/browse/NPA-2679
- Assign `developer.app.id` variable to `Developer-App-Id` header
- Manually tested in main (dev)

NPA-2679 Set Developer APP ID header

---

proxies/live/apiproxy/policies/AssignMessage.AddDeveloperAppData.xml
proxies/live/apiproxy/targets/target.xml

https://nhsd-jira.digital.nhs.uk/browse/NPA-2679
- Assign `developer.app.name` variable to `Developer-App-Name` header
- Manually tested in main (dev)

NPA-2679 Set Developer APP Name Header

---

manifest_template.yml

https://nhsd-jira.digital.nhs.uk/browse/NPA-3336
Add a manual deploy to prod
Make a request to the API GET /RelatedPerson and POST /QuestionnaireResponse endpoints in prod
using the test user:
testuserlive+234@demo.signin.nhs.uk
For authentication

NPA-3336: Add prod env

---

azure/azure-release-pipeline.yml

https://nhsd-jira.digital.nhs.uk/browse/NPA-X3336
Add prod env to build
Run build pipeline

NPM-3336: Add prod

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-3483
- Update OAS Spec to reflect Proxy Application Status changes
- Update `requestedAccess_accessLeve`l from 'Repeat Prescription Requests' to `Request and manage repeat prescriptions`
- Add `NotSpecified` with code `prefer not to say` to `requestedAccess_reasonsForAccess`

NPA-3483 Update OAS spec to reflect PAS changes

---

specification/validated-relationships-service-api.yaml

This PR has broken the VRS API tests.
PRs should be tested against the API tests before merging.
Instructions for how to do this can be found here:
https://github.com/NHSDigital/proxy-validated-relationships-service/blob/5ded4479ac107c967916561b72fd27c806c2444c/tests/README.md?plain=1#L315-L328

Revert "NPA-3543: add initial /Consent endpoint and associated schema refactoring"

---

.vscode/extensions.json
CODE_OF_CONDUCT.md
CONTRIBUTING.md
DEVELOPMENT_GUIDE.md
README.md
SECURITY.md

https://nhsd-jira.digital.nhs.uk/browse/NPA-3332
- `README.md` has been rewritten for a external consumer perspective
- `DEVELOPMENT_GUIDE.md` has been created to host the development/testing/releasing documentation for the schema, proxies and sandbox
- `CONTRIBUTING.md` has been reformatted (with prettier)

NPA-3332 Improve Repository Documentation

---

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml

https://nhsd-jira.digital.nhs.uk/browse/NPA-3922
- Allowed `authorization` - an additional header in the sandbox CORS configuration
- Testing will happen once merged

NPA-3922 Update Sandbox CORS response

---

proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml

https://nhsd-jira.digital.nhs.uk/browse/NPA-3899
- Adds Consent API headers to Sandbox CORS
- Unable to be tested without being deployed to sandbox environment

NPA-3899 Update Sandbox CORS for Consent Headers

---

manifest_template.yml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4421
- Remove Duplicate Internal QA Environment
- Test is after the merge does the workflow break

NPA-4421: Remove Duplicate Internal QA Environment

---

manifest_template.yml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4421
- Updated all environments dev, int and prod to have a rate limit of 10 per second (calculated on a rolling minute). 
- This was agreed by James T in a convo with Adam and I
- I will run a performance test after merge on dev (rate limit has already been tested on QA)

NPA-4421 Increase Rate Limits to 10 Per Second

---

specification/examples/responses/PATCH_Consent/error.yaml
specification/examples/responses/PATCH_Consent/success.yaml
specification/examples/responses/POST_Consent/error.yaml
specification/examples/responses/POST_Consent/success.yaml
specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4313
- Added FHIR-compliant API specification for POST and PATCH operations on the /Consent endpoint for managing proxy relationships
- Added test scenarios and examples for both endpoints
- Added example JSON payloads for common operations including:
- Parent-child proxy creation
- Legal guardian access requests
- Limited access proxy relationships
- Status updates
- Access level modifications
- Verification changes
Review the API specification and examples:
- Verify FHIR resource structures
- Check coding systems used
- Validate response formats
-   [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code …

POST and PATCH specifications for /Consent API

---

postman/Validate_Relationship_Service_Sandbox.postman_collection.json
specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4511
- Postman collection with tests added
- Run postman collection tests
This will run the tests within the collection to check that the sandbox is working as …

NPA-4511: Postman collection added

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4517
- Added headers
-
-
- Verified by manually exporting to swagger.
-
-
This will run the tests within the collection to check that the sandbox is working as …

NPA-4517: Added headers

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4513
- Talked to Adam and split the errors to be more specific
- Update provision to change from list of object to just object as there is a max of 1
- No need …

NPA-4513 Update POST /FHIR/R4/Consent Request and Errors

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4493
- Added bad request as a possible response to mirror responses from the code.
-
-
- N/A - Document change.
-
-
This will run the tests within the collection …

NPA-4493: Added general bad request to POST consent

---

specification/examples/responses/POST_Consent/errors/duplicate_relationship_error.yaml
specification/examples/responses/POST_Consent/errors/invalid_identifier_value.yaml
specification/examples/responses/POST_Consent/errors/invalid_performer_identifier_error.yaml
specification/examples/responses/POST_Consent/errors/invalid_status.yaml
specification/examples/responses/POST_Consent/errors/missing_identifier_system.yaml
specification/examples/responses/POST_Consent/errors/missing_scope.yaml
specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4513
- Expand POST /Consent Error Examples
-
-
-

NPA-4513 Expand POST /Consent Error Examples

---

proxies/live/apiproxy/policies/RaiseFault.403Forbidden.xml
proxies/live/apiproxy/targets/target.xml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4513
- Update 401 error to 403 when user is signed in but has wrong auth level
- API Tests passed:
This will run the tests within the collection to check that …

NPA-4513 Update Authentication Error

---

.github/workflows/openapi-validate.yml
Makefile
postman/Validate Relationship Service Sandbox.postman_collection.json
scripts/validate_schema.py
specification/examples/responses/GET_QuestionnaireResponse/errors/invalid_reference_code.yaml
specification/examples/responses/GET_QuestionnaireResponse/errors/missing_reference_code.yaml
specification/examples/responses/GET_QuestionnaireResponse/errors/questionnaire_response_not_found.yaml
specification/examples/responses/GET_QuestionnaireResponse/success.yaml
specification/examples/responses/POST_QuestionnaireResponse/success.yaml
specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4688
- Add GET QuestionnaireResponse OAS
- Add validate spec and makefile

NPA-4688: Add GET /FHIR/R4/QuestionnaireResponse

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4607
- Add INTERNAL_SERVER_ERROR and DOWNSTREAM_SERVICE_ERROR to PATCH /FHIR/R4/Consent 
-
-
-
This will run the tests within the collection to check that the …

NPA-4607 Add PATCH /FHIR/R4/Consent 5XX Errors

---

specification/validated-relationships-service-api.yaml

- Remove extra ops. Discussed with Simon and Kamran already.
-
-
-
This will run the tests within the collection to check that the sandbox is working as …

NPA-4610 Remove Extra Ops

---

proxies/live/apiproxy/targets/target.xml
specification/validated-relationships-service-api.yaml

- Add new trigger for Incorrect Content-Type error
- Add error to OAS
-
-
-
This will run the tests within the collection to check that the sandbox is …

NPA-4610 Add PATCH /Content Incorrect Media Type Response

---

proxies/live/apiproxy/targets/target.xml

NPA-4610 Update Patch Consent Media Type Condition

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4706
**Changes in Consent Schema**
1. Added id to required
Reason: Every Consent resource should have a unique id
Impact: Ensures every consent record is uniquely identifiable
2. Added status to required
Reason: Status is crucial for determining if the consent is active/rejected/in error
Impact: Enforces clear consent state
3. Added scope to required
Reason: Scope defines the boundaries of consent
Impact: Ensures consent has a clear purpose
4. Added category to required
Reason: Determines type of consent
Impact: Helps with filtering/processing consent based on intended use
5. Added patient to required
Reason: Consent must be linked to a patient
Impact: Prevents consent from being created without a subject
6. Added dateTime to required
Reason: …

NPA-4706: Mark POST Consent Keys As Required

---

proxies/live/apiproxy/targets/target.xml

- Updates PATCH /Consent Content-Type Condition to actually work
- Evidence 
This will run the tests within the collection to check that the sandbox is …

NPA-4610 Update PATCH /Consent Content-Type Condition

---

specification/examples/requests/PATCH_Consent/replace_legal_basis.yaml
specification/validated-relationships-service-api.yaml

- Add replace legal basis example
-
-
-

NPA-4610 Add Replace Legal Basis Example

---

specification/examples/requests/PATCH_Consent/replace_status.yaml
specification/validated-relationships-service-api.yaml

- Add status reason to replace status example
- Add enums for path (PATCH /Consent)
- Add value types (PATCH /Consent)
-
-
-
This will run the tests within …

NPA-4610 Add Status Reason to example and Path enums

---

proxies/live/apiproxy/policies/AssignMessage.AddAuthHeaders.xml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4670
Added App header to Auth Header policy in order to get viewer_identifier_value in the ticket
-
-
-
This will run the tests within the collection to check …

NPA-4670: Add App Header to Auth Header Policy

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4823
- Add PATCH /Consent 4XX Table
- NOTE: DUPLICATE_PATCHES is a new proposed error
-
-
-
This will run the tests within the collection to check that the …

NPA-4823 Construct PATCH /Consent 4XX Table

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4907
- Set MaxItems of 1 for Consent `performer`
Note: This change applies to both the `GET /Consent` response body and `POST /Consent` request body
-
-
-
This …

NPA-4907 Enforce Single Performer Item

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-4891
- Bump Spec version to 1.4.0

NPA-4891 Bump Spec version to 1.4.0

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-5016
- Updated version for specification to v1.5.0
- N/A

NPA-5016: Bump specification Version to 1.5.0

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-5086
- Fix OAS Grammar Issue with using plural for something singular

NPA-5086 Fix OAS Grammar Issue

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-5103
- Updated version for specification to v1.6.0
-
-
-

NPA-5103: Bump OAS Version to 1.6.0

---

proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml

https://nhsd-jira.digital.nhs.uk/browse/NPA-5222
---
- Updated the AssignMessage policy to include PATCH in the Access-Control-Allow-Methods header
---
- TBC
---
---
with
---
---

NPA-52222: Fix PATCH Consent Try It Out Now Defaults

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-5280
---
- Bumped OAS spec version to 1.8.0
---
- N/A
---
---
with
---
---

NPA-5280: Update spec version to v1.8.0

---

specification/examples/responses/GET_Consent/filtered-relationships-status-active-include-details.yaml
specification/examples/responses/GET_Consent/multiple-relationships-include-patient.yaml
specification/examples/responses/GET_Consent/multiple-relationships-include-performer-patient.yaml
specification/examples/responses/GET_Consent/multiple-relationships-single-patient-include-patient.yaml
specification/examples/responses/GET_Consent/multiple-relationships-single-patient-include-performer-patient.yaml
specification/examples/responses/GET_Consent/single-consenting-adult-relationship-include-patient.yaml
specification/examples/responses/GET_Consent/single-consenting-adult-relationship-include-performer-patient.yaml
specification/examples/responses/GET_Consent/single-mother-child-relationship-include-patient.yaml
specification/examples/responses/GET_Consent/single-mother-child-relationship-include-performer-patient.yaml
specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-5431
---
- Updated schema for Consent Bundle Patient resource to include meta object
- Updated examples for GET Consent and GET Consent/{id} to include new security tag
---
- Ran API tests in PVRS pointing to this spec branch and tests were passing
---
---
with
---
---

NPA-5431: Updated OAS and examples with new meta field for security tag

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-5212
---
- 
- 
- 
---
- 
- 
- 
---
---
with
---
---

NPA-5212: version bump V.11.0

---

specification/validated-relationships-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/NPA-5564
---
- Version bump for spec for next release
---
N/A
---
N/A
---
---
---

NPA-5664: Version spec bump to V1.13.0
